runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /(.*\.jpg)
  mime_type: image/jpg
  static_files: static/images/\1
  upload: static/images/(.*\.jpg)

#for minimizing cost
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10